### ISSUE TITLE
rl_roboschool_ray_automatic_model_tuning.ipynb fails to start tuning jobs

### ISSUE THREAD

**Issue by maciejjeicam** [awslabs/amazon-sagemaker-examples#1290]
Hi Team,
can I ask you please to help me resolve issue which I faced where executing ' rl_roboschool_ray_automatic_model_tuning.ipynb' described below?
I am executing the code provided by AWS sagemaker without any change.

At the same point, I executed successfully 'rl_roboschool_ray.ipynb'. Both locally and by submitting a processing job as well.
However, when executing rl_roboschool_ray_automatic_model_tuning.ipynb I get the following error:
Failure reason
AlgorithmError: framework error: Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_trainer.py", line 84, in train entrypoint() File "/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow_container/training.py", line 206, in main model_dir = _model_dir_with_training_job(hyperparameters.get('model_dir'), env.job_name) File "/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow_container/training.py", line 189, in _model_dir_with_training_job if model_dir.startswith('/opt/ml'): AttributeError: 'NoneType' object has no attribute 'startswith' 'NoneType' object has no attribute 'startswith' 

The hyperparameter tuning job fails before it reaches entrypoint script. 
I have no idea how I can further debug the above described issue.

**Comment by maciejjeicam** [comment]
I have few more observations:
- whatever build I provide in RLEstimator e.g. my privite build or official amazon build 763104351884.dkr.ecr.us-east-2.amazonaws.com/tensorflow-training:1.15.2-cpu-py36-ubuntu18.04 the error message is the same as described in my previous comment
- however, if  in RLEstimator  instead of providing 'image_name' I provide: toolkit=RLToolkit.COACH, toolkit_version='0.11.1', framework=RLFramework.TENSORFLOW, the error dissappears.
Of cousrse, the second solution is not acceptable since I would like to execute hyperparameter tuning on my private build.

Any clue what could be the issue?
