### ISSUE TITLE
bandits_statlog_vw_customEnv: Customer Error: Unable to load model (caused by JSONDecodeError)

### ISSUE THREAD

**Issue by tvkpz** [awslabs/amazon-sagemaker-examples#1304]
The bandits statlog Vowpal wabbit example is not able to load the model at the step

bandits_experiment.deploy_model(model_id=bandits_experiment.last_trained_model_id) 

Here is trace:

algo-1-yklna_1  | Caused by: Expecting value: line 1 column 1 (char 0)
algo-1-yklna_1  | Traceback (most recent call last):
algo-1-yklna_1  |   File "/usr/local/lib/python3.6/dist-packages/vw_serving/serve.py", line 235, in get_model
algo-1-yklna_1  |     quiet_mode=True)
algo-1-yklna_1  |   File "/usr/local/lib/python3.6/dist-packages/vw_serving/vw_agent.py", line 289, in load_model
algo-1-yklna_1  |     metadata = json.loads(metadata)
algo-1-yklna_1  |   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
algo-1-yklna_1  |     return _default_decoder.decode(s)
algo-1-yklna_1  |   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
algo-1-yklna_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
algo-1-yklna_1  |   File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
algo-1-yklna_1  |     raise JSONDecodeError("Expecting value", s, err.value) from None
algo-1-yklna_1  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by annaluo676** [comment]
Sorry for the delayed response. From the logs it seems the vw agent is not ready. Can you retry the example, make sure the last retraining is finished and ready for deployment?
