### ISSUE TITLE
mnist-handwritten-digits-classification-experiment.ipynb

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/amazon-sagemaker-examples#1422]
Version 1 - experiments folder: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-experiments/mnist-handwritten-digits-classification-experiment/mnist-handwritten-digits-classification-experiment.ipynb

This is a duplicate of version 2 and should be deleted. 

Version 2 - Studio folder: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/aws_sagemaker_studio/sagemaker_experiments/mnist-handwritten-digits-classification-experiment/mnist-handwritten-digits-classification-experiment.ipynb

* Doesn't work on NI

**Comment by aaronmarkham** [comment]
Also, got a report of this error:

```
UnexpectedStatusException: Error for Training job cnn-training-job-1597798574: Failed. Reason: AlgorithmError: ExecuteUserScriptError:
Command "/usr/bin/python -m mnist --backend gloo --dropout 0.2 --epochs 2 --hidden_channels 2 --kernel_size 5 --optimizer sgd"
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
KeyError: "'time'"
Call stack:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/ml/code/mnist.py", line 227, in <module>
    train(args)
  File "/opt/ml/code/mnist.py", line 85, in train
    logger.debug("Distributed training - {}".format(is_distributed))
Message: 'Distributed training - False'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format
```

**Comment by danabens** [comment]
Hi Aaron, thanks for reporting this issue.

* _duplicate notebooks_ 
  * I'm investigating this.  For now use the notebook in the sagemaker-experiments dir [mnist-handwritten-digits-classification-experiment.ipynb](https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker-experiments/mnist-handwritten-digits-classification-experiment/mnist-handwritten-digits-classification-experiment.ipynb)
* _KeyError: "'time'"_  
  * Fixed in https://github.com/aws/amazon-sagemaker-examples/pull/1576
