### ISSUE TITLE
ValueError: export_outputs must be a dict and not<type 'NoneType'>

### ISSUE THREAD

**Issue by superprachi** [awslabs/amazon-sagemaker-examples#273]
I am new to SageMaker and TensorFlow. I am trying to train a simple CNN binary classifier from scratch on SageMaker. 

I run the following in the notebook instance: 

```
from sagemaker.tensorflow import TensorFlow

dogscats_classifier = TensorFlow(entry_point='classifier.py',
                               role=role,
                               training_steps= 100,                                  
                               evaluation_steps= 100,
                               hyperparameters={'learning_rate': 0.001},
                               train_instance_count=1,
                               train_instance_type='ml.m4.xlarge')

#this s3 directory contains 3 .tfrecords files (train, val, and test)
dogscats_classifier.fit('s3://sagemaker-tutorials1/dogscats/')
```

Here is the code in the 'classifier.py' file:

```import numpy as np
import os
import tensorflow as tf
from tensorflow.python.estimator.export.export import build_raw_serving_input_receiver_fn
from tensorflow.python.estimator.export.export_output import PredictOutput

INPUT_TENSOR_NAME = "image"
SIGNATURE_NAME = "serving_default"
params = {"learning_rate": 0.0001}

def model_fn(features, labels, mode, params):
    # Args:
    #
    # features: This is the x-arg from the input_fn.
    # labels:   This is the y-arg from the input_fn,
    #           see e.g. train_input_fn for these two.
    # mode:     Either TRAIN, EVAL, or PREDICT
    # params:   User-defined hyper-parameters, e.g. learning-rate.
    
    inputs = features[INPUT_TENSOR_NAME]

    # First convolutional layer.
    conv1 = tf.layers.conv2d(inputs, name='layer_conv1',
                           filters=32, kernel_size=3,
                           padding='same', activation=tf.nn.relu)
    pool1 = tf.layers.max_pooling2d(conv1, pool_size=2, strides=2)
    # Second convolutional layer.
    conv2 = tf.layers.conv2d(pool1, name='layer_conv2',
                           filters=64, kernel_size=3,
                           padding='same', activation=tf.nn.relu)
    pool2 = tf.layers.max_pooling2d(conv2, pool_size=2, strides=2)   
    # Third convolutional layer.
    conv3 = tf.layers.conv2d(pool2, name='layer_conv3',
                           filters=128, kernel_size=3,
                           padding='same', activation=tf.nn.relu)
    pool3 = tf.layers.max_pooling2d(conv3, pool_size=2, strides=2)    
    # Flatten to a 2-rank tensor.
    flat = tf.contrib.layers.flatten(pool3)
    # First fully-connected / dense layer.
    # This uses the ReLU activation function.
    dense1 = tf.layers.dense(flat, name='layer_fc1',
                          units=512, activation=tf.nn.relu)    
    # Second fully-connected / dense layer.
    # This is the last layer so it does not use an activation function.
    net = tf.layers.dense(dense1, name='layer_fc2',
                          units=1)
    # Logits output of the neural network.
    logits = net
    # Softmax output of the neural network.
    y_pred = tf.nn.sigmoid(logits)   
    # Classification output of the neural network.
    y_pred_cls = tf.round(y_pred)
    
    if mode == tf.estimator.ModeKeys.PREDICT:
        spec = tf.estimator.EstimatorSpec(mode=mode,
                                          predictions=y_pred_cls)
    else:
        loss = tf.losses.sigmoid_cross_entropy(labels, logits)
        optimizer = tf.train.AdamOptimizer(learning_rate=params["learning_rate"])


        train_op = optimizer.minimize(
            loss=loss, global_step=tf.train.get_global_step())

        metrics = \
        {
            "accuracy": tf.metrics.accuracy(labels, y_pred_cls)
        }

        spec = tf.estimator.EstimatorSpec(
            mode=mode,
            loss=loss,
            train_op=train_op,
            eval_metric_ops=metrics)
        
    return spec

def train_input_fn(training_dir, params):
    print('getting next batch')
    return tfrec_data_input_fn([training_dir+'/train.tfrecords'], 'train/image', 'train/label', num_epochs = None)()

def eval_input_fn(training_dir, params):
    return tfrec_data_input_fn([training_dir+'/val.tfrecords'], 'val/image', 'val/label')()

def tfrec_data_input_fn(filenames, f1, f2, batch_size=64, num_epochs=1, shuffle=False):
    
    def _input_fn_():
        def _parse_record(tf_record):
            features = {
                f1: tf.FixedLenFeature([], dtype=tf.string),
                f2: tf.FixedLenFeature([], dtype=tf.int64)
            }
            record = tf.parse_single_example(tf_record, features)

            image_raw = tf.decode_raw(record[f1], tf.float32)
            image_raw = tf.reshape(image_raw, shape=(224, 224, 3))

            label = tf.cast(record[f2], tf.int32)

            return {'image': image_raw}, label
        
        dataset = tf.data.TFRecordDataset(filenames)
        dataset = dataset.map(_parse_record)

        if shuffle:
            dataset = dataset.shuffle(buffer_size=256)

        dataset = dataset.repeat(num_epochs)
        dataset = dataset.batch(batch_size)

        iterator = dataset.make_one_shot_iterator()
        features, labels = iterator.get_next()
        labels = tf.reshape(labels, shape = [-1,1])
        
        #this line seems a bit redundant, but I'm not sure how to fix it
        return {INPUT_TENSOR_NAME:features['image']}, labels
    
    return _input_fn_

def serving_input_fn(params):
    inputs = {INPUT_TENSOR_NAME: tf.placeholder(tf.float32, [None, 224, 224, 3])}
    return tf.estimator.export.ServingInputReceiver(inputs, inputs)

def _input_fn(addr):
    img = cv2.imread(addr)
    img = cv2.resize(img, (224, 224), interpolation=cv2.INTER_CUBIC)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img.astype(np.float32)
    return img
    
```
I get lots of output ending with the following: 
```2018-06-09 02:11:15,923 INFO - tensorflow - Running local_init_op.
2018-06-09 02:11:15,935 INFO - tensorflow - Done running local_init_op.

2018-06-09 02:11:30,028 INFO - tensorflow - Evaluation [10/100]
2018-06-09 02:11:44,025 INFO - tensorflow - Evaluation [20/100]
2018-06-09 02:11:58,289 INFO - tensorflow - Evaluation [30/100]
2018-06-09 02:12:12,543 INFO - tensorflow - Evaluation [40/100]
2018-06-09 02:12:26,809 INFO - tensorflow - Evaluation [50/100]
2018-06-09 02:12:40,676 INFO - tensorflow - Evaluation [60/100]
2018-06-09 02:12:48,606 INFO - tensorflow - Finished evaluation at 2018-06-09-02:12:48
2018-06-09 02:12:48,607 INFO - tensorflow - Saving dict for global step 1: accuracy = 0.5138095, global_step = 1, loss = 8481.059
2018-06-09 02:12:48.607972: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:48.660267: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404
2018-06-09 02:12:48.660639: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-06-09 02:12:48.661086: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:48.700851: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:48.707369: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404
2018-06-09 02:12:48.707409: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-06-09 02:12:48.707742: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:48.717274: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:48.723421: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404
2018-06-09 02:12:48.723452: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-06-09 02:12:48.723618: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:48.818250: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:48.827162: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20180609T0212481528510368818
2018-06-09 02:12:49.007086: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:49.017162: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:49.027063: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:49.035712: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:49.049672: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:49.092713: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:49.182245: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:49.189743: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:49.218731: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:49.241004: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:49.298589: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:49.306032: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-06-09 02:12:49,320 INFO - tensorflow - Calling model_fn.
2018-06-09 02:12:49,392 INFO - tensorflow - Done calling model_fn.
2018-06-09 02:12:49,396 ERROR - container_support.training - uncaught exception during training: export_outputs must be a dict and not<type 'NoneType'>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 36, in start
    fw.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/train_entry_point.py", line 164, in train
    train_wrapper.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 73, in train
    tf.estimator.train_and_evaluate(estimator=estimator, train_spec=train_spec, eval_spec=eval_spec)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 421, in train_and_evaluate
    executor.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 522, in run
    getattr(self, task_to_run)()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 577, in run_master
    self._start_distributed_training(saving_listeners=saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 715, in _start_distributed_training
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 352, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 891, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 546, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1022, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1113, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1098, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1178, in run
    run_metadata=run_metadata))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 458, in after_run
    self._save(run_context.session, global_step)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 481, in _save
    l.after_save(session, step)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 553, in after_save
    self._evaluator.evaluate_and_export()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 834, in evaluate_and_export
    self._export_eval_result(eval_result, is_the_final_export)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 865, in _export_eval_result
    is_the_final_export=is_the_final_export)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/exporter.py", line 228, in export
    is_the_final_export)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/exporter.py", line 121, in export
    strip_default_attrs=self._strip_default_attrs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 598, in export_savedmodel
    serving_input_receiver.receiver_tensors_alternatives)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/export/export.py", line 199, in build_all_signature_defs
    '{}'.format(type(export_outputs)))
ValueError: export_outputs must be a dict and not<type 'NoneType'>
```
Am I messing up something simple here?
Also, why is it calling python2.7 when I am using the conda_tensorflow_p36 kernel?

**Comment by jesterhazy** [comment]
@superprachi for predict mode, you need to provide the export_output argument to the EstimatorSpec. Check out this sample code:

https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/census/customestimator/trainer/model.py#L199
