### ISSUE TITLE
scikit-learn build your own local_test train_local.sh

### ISSUE THREAD

**Issue by gregroberts** [awslabs/amazon-sagemaker-examples#283]
# Background
Running through the "Scikit-Learn build your own" example, and trying to execute the train_local.sh & serve_local.sh scripts does not work.

# Error

Spin up a sagemaker notebook instance, log into the notebook server, start the
    `/sample-notebooks/advanced_functionality/scikit_bring_your_own/scikit_bring_your_own.ipynb`

notebook. Run all the steps up to and including building the image and pushing it to ECR.

## serve_local.sh

Using the existing model artefact:

In a new Notebook instance in the same folder, attempt to run the serve_local script by running the  following in a cell:

`
%%sh
bash container/local_test/serve_local.sh decision-trees-sample
`

Then, in the first notebook, use the predict script & the payload csv to test the local running instance:

`
%%sh
bash container/local_test/predict.sh container/local_test/payload.csv text/csv
`

this returns the output:

`

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /invocations HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.60.0
> Accept: */*
> Content-Type: text/csv
> Content-Length: 2900
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
} [2900 bytes data]
* We are completely uploaded and fine
< HTTP/1.1 500 INTERNAL SERVER ERROR
< Server: nginx/1.10.3 (Ubuntu)
< Date: Wed, 13 Jun 2018 09:17:35 GMT
< Content-Type: text/html
< Content-Length: 291
< Connection: keep-alive
< 
{ [291 bytes data]
100  3191  100   291  100  2900  32333   314k --:--:-- --:--:-- --:--:--  346k
* Connection #0 to host localhost left intact
`

## train_local.sh

To replicate this, delete the model artefacts which are in the local_test dir to begin with:

`%rm -f container/local_test/test_dir/model/decision-tree-model.pkl`

Before running the `## Create an estimator and fit the model` step, attempt to run the local training script from the notebook instance by running the following in a cell in the Notebook:

`
%%sh
bash container/local_test/train_local.sh decision-trees-sample
`

Which returns the output:

`
Starting the training.
rm: cannot remove ‘test_dir/model/*’: No such file or directory
Exception during training: [Errno 2] No such file or directory: '/opt/ml/input/config/hyperparameters.json'
Traceback (most recent call last):
  File "/opt/program/train", line 38, in train
    with open(param_path, 'r') as tc:
IOError: [Errno 2] No such file or directory: '/opt/ml/input/config/hyperparameters.json'
`

# Attempts 

- I don't have any ideas here :(

**Comment by djarpin** [comment]
Hi @gregroberts .  Sorry you're having troubles.  Can you try using the command to run these commands (starting from the `container` directory of the example?

```bash
$ bash build_and_push.sh scitrees
$ cd local_test/
$ bash train_local.sh scitrees
$ bash serve_local.sh scitrees &
$ bash predict.sh payload.csv
```

Your write-up is helpful, but it's a bit difficult to tell where the problem might be slipping in across the multiple notebooks, etc.  Thanks.

**Comment by djarpin** [comment]
Closing due to inactivity.  Feel free to re-open if necessary.  Thanks.

**Comment by vlad31** [comment]
@djarpin I ran into the same problem. Cloned the repo, ran all the commands specified above and got various errors. The first command works, and the docker image gets registered in the ECS repo. However when I run `bash train_local.sh scitrees` the error output is:

```
rm: test_dir/model/*: No such file or directory
rm: test_dir/output/*: No such file or directory
Traceback (most recent call last):
  File "/opt/program/train", line 17, in <module>
    from sklearn import tree
  File "/usr/local/lib/python2.7/dist-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/usr/local/lib/python2.7/dist-packages/sklearn/base.py", line 13, in <module>
    from .utils.fixes import signature
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/__init__.py", line 16, in <module>
    from .fixes import _Sequence as Sequence
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/fixes.py", line 85, in <module>
    from scipy.special import boxcox  # noqa
  File "/usr/local/lib/python2.7/dist-packages/scipy/special/__init__.py", line 641, in <module>
    from ._ufuncs import *
ImportError: libopenblasp-r0-8dca6697.3.0.dev.so: cannot open shared object file: No such file or directory
```

If I remove the import statement (_from sklearn import tree_) I get this error:
```
rm: test_dir/model/*: No such file or directory
rm: test_dir/output/*: No such file or directory
Starting the training.
Exception during training: [Errno 2] No such file or directory: '/opt/ml/input/config/hyperparameters.json'
Traceback (most recent call last):
  File "/opt/program/train", line 40, in train
    with open(param_path, 'r') as tc:
IOError: [Errno 2] No such file or directory: '/opt/ml/input/config/hyperparameters.json'
```
