### ISSUE TITLE
Error running Keras example notebook

### ISSUE THREAD

**Issue by FarhanTejani** [awslabs/amazon-sagemaker-examples#305]
I am trying to run the CIFAR10 Keras notebook [here](https://github.com/awslabs/amazon-sagemaker-examples/blob/mvs-keras-notebook/sagemaker-python-sdk/tensorflow_keras_cifar10/tensorflow_keras_CIFAR10.ipynb) on SageMaker, but I run into the following error when I try to create the training job:

```
ValueError: Error training sagemaker-tensorflow-2018-07-04-02-30-42-260: Failed Reason: AlgorithmError: uncaught exception during training: 'Sequential' object has no attribute 'train_function'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 36, in start
    fw.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/train_entry_point.py", line 164, in train
    train_wrapper.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 69, in train
    estimator = self._build_estimator(run_config=run_config)
  File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 96, in _build_estimator
    return tf.keras.estimator.model_to_estimator(keras_model=model, config=run_config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/estimator.py", line 504, in model_to_estimator
    keras_weights)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/estimator.py", line 415, in _save_first_checkpoint
    if not model.train_function:
AttributeError: 'Sequential' object has no attribute 'train_function'
```

I have looked at the Keras estimator code where it is failing [here](https://github.com/tensorflow/tensorflow/blob/b390be62ad0514f4fd3347b9db3446c84e08a38e/tensorflow/python/estimator/keras.py#L450) and it seems like the model returned by `_clone_and_build_model(...)` is not properly wrapping the Keras model so that it has a `train_function`.

**Comment by FarhanTejani** [comment]
This seems to be a problem with Tensorflow and not SageMaker in particular. I found a relevant issue in the Tensorflow repo [here](https://github.com/tensorflow/tensorflow/issues/20552), so I will close this issue and follow that one.
