### ISSUE TITLE
scikit_bring_your_own local test

### ISSUE THREAD

**Issue by samsammurphy** [awslabs/amazon-sagemaker-examples#342]
When running through the [scikit byom](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/scikit_bring_your_own.ipynb) example, I hit an error when trying to run the local test..

```
$ ./serve_local.sh e7ea36fc1eda
Starting the inference server with 4 workers.
[2018-07-25 13:43:08 +0000] [10] [INFO] Starting gunicorn 19.9.0
[2018-07-25 13:43:08 +0000] [10] [INFO] Listening at: unix:/tmp/gunicorn.sock (10)
[2018-07-25 13:43:08 +0000] [10] [INFO] Using worker: gevent
[2018-07-25 13:43:08 +0000] [15] [INFO] Booting worker with pid: 15
[2018-07-25 13:43:08 +0000] [16] [INFO] Booting worker with pid: 16
[2018-07-25 13:43:08 +0000] [17] [INFO] Booting worker with pid: 17
[2018-07-25 13:43:08 +0000] [18] [INFO] Booting worker with pid: 18
/usr/local/lib/python2.7/dist-packages/gevent/builtins.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  result = _import(*args, **kwargs)
```

wondering if I could just ignore it I opened another terminal and tried to make a prediction 

```
$ ./predict.sh payload.csv text/csv
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /invocations HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: text/csv
> Content-Length: 2900
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 500 INTERNAL SERVER ERROR
< Server: nginx/1.10.3 (Ubuntu)
< Date: Wed, 25 Jul 2018 13:48:05 GMT
< Content-Type: text/html
< Content-Length: 291
< Connection: keep-alive
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
* Connection #0 to host localhost left intact
```

In the original terminal running the server I get the following error

> ImportError: libopenblasp-r0-39a31c03.2.18.so: cannot open shared object file: No such file or directory

The full stack trace is

```
$ ./serve_local.sh e7ea36fc1eda
Starting the inference server with 4 workers.
[2018-07-25 13:43:08 +0000] [10] [INFO] Starting gunicorn 19.9.0
[2018-07-25 13:43:08 +0000] [10] [INFO] Listening at: unix:/tmp/gunicorn.sock (10)
[2018-07-25 13:43:08 +0000] [10] [INFO] Using worker: gevent
[2018-07-25 13:43:08 +0000] [15] [INFO] Booting worker with pid: 15
[2018-07-25 13:43:08 +0000] [16] [INFO] Booting worker with pid: 16
[2018-07-25 13:43:08 +0000] [17] [INFO] Booting worker with pid: 17
[2018-07-25 13:43:08 +0000] [18] [INFO] Booting worker with pid: 18
/usr/local/lib/python2.7/dist-packages/gevent/builtins.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  result = _import(*args, **kwargs)
/usr/local/lib/python2.7/dist-packages/gevent/builtins.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  result = _import(*args, **kwargs)
/usr/local/lib/python2.7/dist-packages/gevent/builtins.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  result = _import(*args, **kwargs)
/usr/local/lib/python2.7/dist-packages/gevent/builtins.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  result = _import(*args, **kwargs)
Invoked with 29 records
[2018-07-25 13:48:05,146] ERROR in app: Exception on /invocations [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/program/predictor.py", line 76, in transformation
    predictions = ScoringService.predict(data)
  File "/opt/program/predictor.py", line 42, in predict
    clf = cls.get_model()
  File "/opt/program/predictor.py", line 32, in get_model
    cls.model = pickle.load(inp)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1130, in find_class
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/__init__.py", line 134, in <module>
    from .base import clone
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/base.py", line 13, in <module>
    from .utils.fixes import signature
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/__init__.py", line 10, in <module>
    from .validation import (as_float_array,
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 18, in <module>
    from ..utils.fixes import signature
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/fixes.py", line 144, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scipy/sparse/linalg/__init__.py", line 114, in <module>
    from .isolve import *
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scipy/sparse/linalg/isolve/__init__.py", line 6, in <module>
    from .iterative import *
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scipy/sparse/linalg/isolve/iterative.py", line 10, in <module>
    from . import _iterative
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
ImportError: libopenblasp-r0-39a31c03.2.18.so: cannot open shared object file: No such file or directory
172.17.0.1 - - [25/Jul/2018:13:48:05 +0000] "POST /invocations HTTP/1.1" 500 316 "-" "curl/7.47.0"
```
The only thing I think I changed was the algorithm name in this bash script..

```
%%sh

# The name of our algorithm
algorithm_name=decision-trees-sample
```

so I don't *think* I broke anything

any ideas?

**Comment by titanjer** [comment]
I got this error as well.
This example does not freeze `numpy` version, the working version is `1.14.5`. I tried OK last week.
You can modify the Dockerfile or migrate example code to `1.15.0`.

**Comment by samsammurphy** [comment]
@titanjer yep, that worked. :tada:  thanks :pray:

**Comment by djarpin** [comment]
Thanks for jumping in an contributing the fix for this @samsammurphy and @titanjer !
