### ISSUE TITLE
pytorch and mxnet examples gave me <!DOCTYPE html>     ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by haol0816** [awslabs/amazon-sagemaker-examples#439]
I was replicating pytorch and mxnet examples on my own AWS account. One example I tried was https://github.com/awslabs/amazon-sagemaker-examples/tree/master/sagemaker-python-sdk/pytorch_lstm_word_language_model
I manually copied everything from GitHub to my SageMaker notebook instance, I did not make any changes. but the estimator.fit() always gave me the following error:
```
2018-10-12 20:35:49,618 sagemaker-containers ERROR    ExecuteUserScriptError:
Command "/usr/bin/python -m train --epochs 6 --tied True"
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 144, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/train.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

**Comment by haol0816** [comment]
I think I know what happened. my download process introduced additional characters.  Sorry. I will close this issue
