### ISSUE TITLE
ImportError: libcuda.so.1

### ISSUE THREAD

**Issue by shoegazerstella** [awslabs/amazon-sagemaker-examples#632]
Hello,
My code is running on sagemaker in a docker container.
Docker image: `tensorflow/tensorflow:latest-gpu`
Python version: `2.7`
Keras version: `2.1.6`

This code was running fine about 1 month ago. Now I have this error when importing keras:

```
Using TensorFlow backend.
Traceback (most recent call last):
File "train.py", line 14, in <module>
from keras.callbacks import EarlyStopping, ModelCheckpoint # , TensorBoard
File "/usr/local/lib/python2.7/dist-packages/keras/__init__.py", line 3, in <module>
from . import utils
File "/usr/local/lib/python2.7/dist-packages/keras/utils/__init__.py", line 6, in <module>
from . import conv_utils
File "/usr/local/lib/python2.7/dist-packages/keras/utils/conv_utils.py", line 9, in <module>
from .. import backend as K
File "/usr/local/lib/python2.7/dist-packages/keras/backend/__init__.py", line 84, in <module>
from .tensorflow_backend import *
File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
import tensorflow as tf
File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
from tensorflow.python import pywrap_tensorflow
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
from tensorflow.python.pywrap_tensorflow_internal import *
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
_pywrap_tensorflow_internal = swig_import_helper()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)

ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors
for some common reasons and solutions. Include the entire stack trace
above this error message when asking for help.
```

I tried to downgrade tensorflow-gpu to versions 1.0, 1.4, 1.5 and I still get cuda errors.
Thanks for your help.

**Comment by shoegazerstella** [comment]
Solved using this:
`FROM tensorflow/tensorflow:1.12.0-gpu`
There must be something wrong on the latest tensorflow-gpu docker image when on aws.
