### ISSUE TITLE
Docker build fails in the rl_roboschool_ray example

### ISSUE THREAD

**Issue by hariby** [awslabs/amazon-sagemaker-examples#638]
The [`rl_roboschool_ray`](https://github.com/awslabs/amazon-sagemaker-examples/tree/master/reinforcement_learning/rl_roboschool_ray) example provides a notebook [`rl_roboschool_ray.ipynb`](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/reinforcement_learning/rl_roboschool_ray/rl_roboschool_ray.ipynb) to demonstrate RL training. 

In the `Build docker container` section of the notebook, it guides to execute [`build_and_push_docker_image`](https://github.com/awslabs/amazon-sagemaker-examples/blob/a3e9b4ae61b518416aaed06588f589bbc728f10b/reinforcement_learning/rl_roboschool_ray/common/docker_utils.py#L32) function using a [Dockerfile](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/reinforcement_learning/rl_roboschool_ray/Dockerfile). 

I tried in several environments (SageMaker Notebook instance and MacBook Pro with pyenv/anaconda3-5.1.0/JupyterLab), It fails with the same message as below: 
```
Step 15/16 : RUN python -c "import gym;import sagemaker_containers.cli.train; import roboschool; import ray; from sagemaker_containers.cli.train import main"
 ---> Running in 1b2a22054153
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/roboschool/roboschool/__init__.py", line 112, in <module>
    from roboschool.gym_pendulums import RoboschoolInvertedPendulum
  File "/opt/roboschool/roboschool/gym_pendulums.py", line 1, in <module>
    from roboschool.scene_abstract import SingleRobotEmptyScene
  File "/opt/roboschool/roboschool/scene_abstract.py", line 12, in <module>
    from roboschool  import cpp_household   as cpp_household
ImportError: cannot import name 'cpp_household'
The command '/bin/sh -c python -c "import gym;import sagemaker_containers.cli.train; import roboschool; import ray; from sagemaker_containers.cli.train import main"' returned a non-zero code: 1
```
followed by the output 
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/SageMaker/rl_roboschool_ray_2019-02-22/common/docker_utils.py in _execute(command, quiet)
    167     try:
--> 168         _stream_output(process)
    169     except RuntimeError as e:

~/SageMaker/rl_roboschool_ray_2019-02-22/common/docker_utils.py in _stream_output(process)
    195     if exit_code != 0:
--> 196         raise RuntimeError("Process exited with code: %s" % exit_code)
    197 

RuntimeError: Process exited with code: 1

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<timed exec> in <module>()

~/SageMaker/rl_roboschool_ray_2019-02-22/common/docker_utils.py in build_and_push_docker_image(repository_name, dockerfile, build_args)
     38     base_image = _find_base_image_in_dockerfile(dockerfile)
     39     _ecr_login_if_needed(base_image)
---> 40     _build_from_dockerfile(repository_name, dockerfile, build_args)
     41     ecr_tag = push(repository_name)
     42     return ecr_tag

~/SageMaker/rl_roboschool_ray_2019-02-22/common/docker_utils.py in _build_from_dockerfile(repository_name, dockerfile, build_args)
     49 
     50     print("Building docker image %s from %s" % (repository_name, dockerfile))
---> 51     _execute(build_cmd)
     52     print("Done building docker image %s" % repository_name)
     53 

~/SageMaker/rl_roboschool_ray_2019-02-22/common/docker_utils.py in _execute(command, quiet)
    171         # which contains the exit code and append the command line to it.
    172         msg = "Failed to run: %s, %s" % (command, str(e))
--> 173         raise RuntimeError(msg)
    174 
    175 

RuntimeError: Failed to run: ['docker', 'build', '-t', 'sagemaker-roboschool-ray-cpu', '-f', 'Dockerfile', '.', '--build-arg', 'CPU_OR_GPU=cpu', '--build-arg', 'AWS_REGION=us-east-1'], Process exited with code: 1
```
with the [latest commit](https://github.com/awslabs/amazon-sagemaker-examples/commit/7509363d76c2dec0dd6b47b4e5ee1bd641f86558). 

Any help is greatly appreciated. 
Thanks

**Comment by PaulConyngham** [comment]
Hi I am getting this same error error listed above by @hariby  - would be great if the author might be able to comment?

**Comment by PaulConyngham** [comment]
Also @hariby were you able to get this working by using an older version of the script by any chance?

**Comment by PaulConyngham** [comment]
the docker build also fails for the distributed example

**Comment by haje01** [comment]
I get the same error. I've tested Seoul & N. Virginia regions. They both have the same error: 
"ImportError: cannot import name 'cpp_household'"

**Comment by saurabh3949** [comment]
The issue was fixed with https://github.com/awslabs/amazon-sagemaker-examples/pull/726 .
Can you please try again?

**Comment by haje01** [comment]
I've checked it. Docker build succeeds! Thank you.
