### ISSUE TITLE
docker-compose command fails when running mxnet predict

### ISSUE THREAD

**Issue by RustyRaptor** [awslabs/amazon-sagemaker-examples#807]
I am trying to run the local training mode for the mxnet_gluon_cifar10 example folder. I am able to run the training and all but when I try to deploy the predictor it does this.

```
predictor = m.deploy(initial_instance_count=1, instance_type='local_gpu')

```
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sagemaker/local/image.py", line 542, in run
    _stream_output(self.process)
  File "/usr/local/lib/python3.6/dist-packages/sagemaker/local/image.py", line 604, in _stream_output
    raise RuntimeError("Process exited with code: %s" % exit_code)
RuntimeError: Process exited with code: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/sagemaker/local/image.py", line 547, in run
    raise RuntimeError(msg)
RuntimeError: Failed to run: ['docker-compose', '-f', '/tmp/tmpxkw6jkfy/docker-compose.yaml', 'up', '--build', '--abort-on-container-exit'], Process exited with code: 1

-----------------------------------------------------
RuntimeError        Traceback (most recent call last)
<ipython-input-22-09117cc2243b> in <module>
----> 1 predictor = m.deploy(initial_instance_count=1, instance_type='local_gpu')

/usr/local/lib/python3.6/dist-packages/sagemaker/estimator.py in deploy(self, initial_instance_count, instance_type, accelerator_type, endpoint_name, use_compiled_model, update_endpoint, wait, model_name, **kwargs)
    453             update_endpoint=update_endpoint,
    454             tags=self.tags,
--> 455             wait=wait,
    456         )
    457 

/usr/local/lib/python3.6/dist-packages/sagemaker/model.py in deploy(self, initial_instance_count, instance_type, accelerator_type, endpoint_name, update_endpoint, tags, kms_key, wait)
    386         else:
    387             self.sagemaker_session.endpoint_from_production_variants(
--> 388                 self.endpoint_name, [production_variant], tags, kms_key, wait
    389             )
    390 

/usr/local/lib/python3.6/dist-packages/sagemaker/session.py in endpoint_from_production_variants(self, name, production_variants, tags, kms_key, wait)
   1216 
   1217             self.sagemaker_client.create_endpoint_config(**config_options)
-> 1218         return self.create_endpoint(endpoint_name=name, config_name=name, tags=tags, wait=wait)
   1219 
   1220     def expand_role(self, role):

/usr/local/lib/python3.6/dist-packages/sagemaker/session.py in create_endpoint(self, endpoint_name, config_name, tags, wait)
    877 
    878         self.sagemaker_client.create_endpoint(
--> 879             EndpointName=endpoint_name, EndpointConfigName=config_name, Tags=tags
    880         )
    881         if wait:

/usr/local/lib/python3.6/dist-packages/sagemaker/local/local_session.py in create_endpoint(self, EndpointName, EndpointConfigName, Tags)
    185         endpoint = _LocalEndpoint(EndpointName, EndpointConfigName, Tags, self.sagemaker_session)
    186         LocalSagemakerClient._endpoints[EndpointName] = endpoint
--> 187         endpoint.serve()
    188 
    189     def update_endpoint(self, EndpointName, EndpointConfigName):  # pylint: disable=unused-argument

/usr/local/lib/python3.6/dist-packages/sagemaker/local/entities.py in serve(self)
    397 
    398         serving_port = get_config_value("local.serving_port", self.local_session.config) or 8080
--> 399         _wait_for_serving_container(serving_port)
    400         # the container is running and it passed the healthcheck status is now InService
    401         self.state = _LocalEndpoint._IN_SERVICE

/usr/local/lib/python3.6/dist-packages/sagemaker/local/entities.py in _wait_for_serving_container(serving_port)
    426         i += 5
    427         if i >= HEALTH_CHECK_TIMEOUT_LIMIT:
--> 428             raise RuntimeError("Giving up, endpoint didn't launch correctly")
    429 
    430         logger.info("Checking if serving container is up, attempt: %s", i)

RuntimeError: Giving up, endpoint didn't launch correctly
```

When I try to run the command that's failing in the terminal I get...
```
docker-compose -f /tmp/tmpxkw6jkfy/docker-compose.yaml up --build
Starting tmpxkw6jkfy_algo-1-t97fn_1 ... error

ERROR: for tmpxkw6jkfy_algo-1-t97fn_1  Cannot start service algo-1-t97fn: driver failed programming external connectivity on endpoint tmpxkw6jkfy_algo-1-t97fn_1 (6f76b65eb55ea66367751d02512449f518d9575f1b73449c5ee145c8c9ce8728): Bind for 0.0.0.0:8080 failed: port is already allocated

ERROR: for algo-1-t97fn  Cannot start service algo-1-t97fn: driver failed programming external connectivity on endpoint tmpxkw6jkfy_algo-1-t97fn_1 (6f76b65eb55ea66367751d02512449f518d9575f1b73449c5ee145c8c9ce8728): Bind for 0.0.0.0:8080 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```
I am able to get it to work if I edit the yaml file manually but im guessing it needs to run with the predictor code. I cannot change the port number for the generated yaml file. It just creates a new one with port 8080 each time. Is there a way to configure it to use a different default port/

**Comment by RustyRaptor** [comment]
Ok so this is working now but now I'm getting a different but related issue.
