### ISSUE TITLE
error when run the mxnet_gluon_sentiment exmaple with my own data

### ISSUE THREAD

**Issue by bbgky** [awslabs/amazon-sagemaker-examples#835]
I was following the example:
https://github.com/awslabs/amazon-sagemaker-examples/tree/master/sagemaker-python-sdk/mxnet_gluon_sentiment
only thing i  tried to change is using my own data.
model starts to train but after some time it gave the `mxnet.base.MXNetError` which i really don't understand what i am doing wrong
```
[Epoch 0 Batch 1000] Training: f1=0.409607, 362.206328 samples/s
[Epoch 0 Batch 2000] Training: f1=0.436837, 204.416968 samples/s
[Epoch 0 Batch 3000] Training: f1=0.456156, 148.073890 samples/s
[Epoch 0 Batch 4000] Training: f1=0.472044, 129.264817 samples/s
[Epoch 0 Batch 5000] Training: f1=0.478562, 118.087454 samples/s
[Epoch 0 Batch 6000] Training: f1=0.485318, 107.069591 samples/s
[Epoch 0 Batch 7000] Training: f1=0.487679, 107.611444 samples/s
[Epoch 0 Batch 8000] Training: f1=0.489748, 97.415370 samples/s
[Epoch 0 Batch 9000] Training: f1=0.491267, 100.856133 samples/s
[Epoch 0 Batch 10000] Training: f1=0.496632, 96.826172 samples/s
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/ml/code/sentiment.py", line 336, in <module>
    args.batch_size, args.epochs, args.learning_rate, args.log_interval, args.embedding_size)
  File "/opt/ml/code/sentiment.py", line 84, in train
    L.backward()
  File "/usr/local/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 2200, in backward
    ctypes.c_void_p(0)))
  File "/usr/local/lib/python3.6/site-packages/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:17:49] src/imperative/./imperative_utils.h:598: Check failed: g.GetAttr<size_t>("shape_num_unknown_nodes") == 0U (4 vs. 0) 

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x21d8d4) [0x7f55d1e788d4]
[bt] (1) /usr/local/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x21dcb1) [0x7f55d1e78cb1]
[bt] (2) /usr/local/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2bd8515) [0x7f55d4833515]
[bt] (3) /usr/local/lib/python3.6/site-packages/mxnet/libmxnet.so(mxnet::Imperative::Backward(std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, bool, bool, bool)+0x2660) [0x7f55d4863b60]
[bt] (4) /usr/local/lib/python3.6/site-packages/mxnet/libmxnet.so(MXAutogradBackwardEx+0x573) [0x7f55d4768293]
[bt] (5) /usr/local/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7f55e2df13a6]
[bt] (6) /usr/local/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call+0x3f1) [0x7f55e2df0101]
[bt] (7) /usr/local/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2cf) [0x7f55e2de77bf]
[bt] (8) /usr/local/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x9719) [0x7f55e2dde719]
[bt] (9) /usr/local/bin/python3.6(_PyObject_FastCallDict+0xa2) [0x453e32]
```

**Comment by laurenyu** [comment]
hi @bbgky, sorry for the delay in response!

can you give more detail about the data you're using? how does it differ from the data originally used in the sample notebook?

**Comment by bbgky** [comment]
Hi @laurenyu 
This issue could be closed, I am not working on it anymore. Thanks
